version: '3.8'

services:
  pve-telegram-bot:
    build: .
    container_name: pve-telegram-bot
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ~/.ssh:/root/.ssh:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
